#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $BABY_REPO == "BABYBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1cySEdhbGF4eS1PUC9XMkhVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $BABY_REPO == "BABYBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1cySEdhbGF4eS1PUC9XMkhVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $BABY_REPO =~ $regex ]]
    then
        if [[ $W2H_REPO_BRANCH ]]
        then
            echo "${BABY_REPO}/archive/${BABY_REPO_BRANCH}.zip"
        else
            echo "${BABY_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1cySEdhbGF4eS1PUC9XMkhVc2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="BABYBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    BABYPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $BABYPATH
    echo "    Starting BABYBot    "
    echo "
    W2HBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
